export { hzToMidi, midiToNoteName } from './pitch.ts';
export type {
  MelodySource,
  MelodyNote,
  ScaleDegree,
  ScaleDegreeEvidence,
  TonalMode,
  TonalCenterSegment,
  MusicalDomain,
  MusicalCapabilities,
  MelodyPitchFrame,
  MelodyAnalysis,
  PercussionKind,
  PercussionDescriptors,
  PercussionHit,
  PercussionAnalysis,
  RhythmSection,
  TempoCandidate,
  BeatMarker,
  RhythmAnalysis,
  HarmonyRegion,
  ChordCandidateSummary,
  ChromaFrame,
  ChordSegment,
  HarmonyAnalysis,
  TonalCenterCandidate,
  TonalCenterFrame,
  TonalCenterAnalysis,
  StructureAnalysisFrame,
  StructureBoundary,
  ArrangementChange,
  StructureSegment,
  StructureAnalysis,
  SpectrumRegion,
  AudioAmplitudeRegion,
  AudioAnalysisMetadata,
  ListeningMap,
} from './types.ts';
export * from './melody-evidence/types.ts';
